config/routes.rb
Rails.application.routes.draw do
  get 'purposes/index'

  root             'static_pages#home'

  get 'signup'  => 'users#new'

  resources :users
  resources :kinds
  resources :transactions
  resources :purposes

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  post   'login'   => 'sessions#create'

  get   'test_user'   => 'sessions#login_test_user'

  get 'recharge' => 'users#recharge'
  post 'recharge' => 'users#add_money'

  get 'purpose_recharge' => 'purposes#recharge'
  post 'purpose_recharge' => 'purposes#add_money'



  get 'data-filter' => 'transactions#data_filer_show'
  get 'category-filter' => 'transactions#category_filter_show'
  get 'money-filter' => 'transactions#money_filter_show'

  get 'chart' => 'charts#index'
  get 'three_month' => 'charts#three_month'
  get 'month' => 'charts#month'
  get 'today' => 'charts#today'

end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
    @user=current_user
    @transaction = Transaction.unscoped.where(:user_id => @user.id)
  end

  def three_month
   @user=current_user
   @current_user_transaction = Transaction.unscoped.where(:user_id => @user.id)
   @transaction = @current_user_transaction.where(["created_at::date >= ?", 3.month.ago])
   render 'index'
  end

   def month
    @user=current_user
    @current_user_transaction = Transaction.unscoped.where(:user_id => @user.id)
    @transaction = @current_user_transaction.where(["created_at::date >= ?", 1.month.ago])
    render 'index'
   end

   def today
    @user=current_user
    @current_user_transaction = Transaction.unscoped.where(:user_id => @user.id)
    @transaction = @current_user_transaction.where(["created_at::date = ?", Date.today])
    render 'index'
   end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/index.html.erb
<%= content_for :content do %>

<%= javascript_include_tag "http://code.highcharts.com/highcharts.js", "chartkick" %>

    <h3>Charts</h3>

    <p>
    <%= link_to "All time", :controller => :charts, :action => :index  %> /
    <%= link_to "3 month", three_month_path  %> /
    <%= link_to "Month", month_path  %> /
    <%= link_to "Today", today_path  %>
    </p>

    <h4>Statistic</h4>
    <table class="table ">
      <tr>
        <th>Transactions count</th>
        <th>Money</th>
      </tr>
      <tr>
        <td><%= @transaction.count %></td>
        <td> - <%= @transaction.sum(:price) %></td>
      </tr>
    </table>
<hr>
    <h4>Transaction</h4>
    <%= bar_chart @transaction.group(:name).sum(:price) %>
<hr>

    <h4>Transaction by data</h4>
    <%= area_chart @transaction.group(:kind_name).group_by_day(:created_at).sum(:price) %>
<hr>
    <h4>Category</h4>
    <%= pie_chart @transaction.group(:kind_name).sum(:price) %>




<% end %>