config/routes.rb
Rails.application.routes.draw do
  get 'purposes/index'

  root             'static_pages#home'

  get 'signup'  => 'users#new'

  resources :users
  resources :kinds
  resources :transactions
  resources :purposes

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  post   'login'   => 'sessions#create'

  get   'test_user'   => 'sessions#login_test_user'

  get 'recharge' => 'users#recharge'
  post 'recharge' => 'users#add_money'

  get 'purpose_recharge' => 'purposes#recharge'
  post 'purpose_recharge' => 'purposes#add_money'



  get 'data-filter' => 'transactions#data_filer_show'
  get 'category-filter' => 'transactions#category_filter_show'
  get 'money-filter' => 'transactions#money_filter_show'

  get 'chart' => 'charts#index'
  get 'three_month' => 'charts#three_month'
  get 'month' => 'charts#month'
  get 'today' => 'charts#today'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :logged_in_user

  def new
    @transaction = Transaction.new()
  end

  def index
    @require_kinds_names = []
    @kinds_names_from_transactions = []
    @foo = []
    @user = current_user
    @new = Transaction.new()
    @transaction_before = Transaction.where(:user_id => @user.id)
    @transaction = @transaction_before.paginate(:page => params[:page], :per_page => 15).order('id DESC')

    @transaction_remaining = @transaction_before.where(["created_at >= ?", 1.month.ago])

    @arr = Kind.where(:user_id=>@user.id)
    @require_kinds = @arr.where(:isRequire => true)

    @require_kinds.each do |f|
      @require_kinds_names << f.name
    end

    @transaction_remaining.each do |f|
    @kinds_names_from_transactions << f.kind_name
    end

    @require_kinds_names.each do |name|
      if !@kinds_names_from_transactions.include?(name)
        @foo << name
      end
    end
   end


  def create
    @user = current_user
    if @user.id != 1
    @was = @user.balance
    @kind_id = params[:transaction][:kind_id]
    @kind_name = Kind.find(@kind_id).name
    @transaction = Transaction.new(:name=>params[:transaction][:name], :price=>params[:transaction][:price],
                                   :kind_id=>params[:transaction][:kind_id], :user_id=>@user.id,
     :kind_name=>@kind_name)

    if @was>params[:transaction][:price].to_f
        if @transaction.save
          @user.update_attributes(balance: @was - params[:transaction][:price].to_f)
          # Handle a successful save.
          flash[:success] = "New transaction added"
          redirect_to transactions_url
        else
          render 'new'
        end
    else
      flash[:danger] = "payment cant be higher than your balance"
      redirect_to transactions_url
    end
    else
      flash[:info] = "Are yor ready to sign up the Warden? Log out this awesome test user if you are!"
      redirect_to transactions_url
    end
   end

  def edit
    @user = current_user
    @transaction = Transaction.find(params[:id])
  end

  def update
    @user = current_user
    if @user.id != 1
    @balance_was = @user.balance
    @transaction = Transaction.find(params[:id])
    @transaction_price_was = @transaction.price
    @kind_id = params[:transaction][:kind_id]
    @kind_name = Kind.find(@kind_id).name

    if @transaction.update_attributes(transaction_params)
      @user.update_attributes(balance: @balance_was + @transaction_price_was - params[:transaction][:price].to_f )
      @transaction.update_attributes(:kind_name=>@kind_name)
      # Handle a successful update.
      flash[:success] = "Transaction updated"
      redirect_to transactions_url
    else
      render 'edit'
    end
    else
      flash[:info] = "Are yor ready to sign up the Warden? Log out this awesome test user if you are!"
      redirect_to transactions_url
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    user = current_user
    if user.id != 1
    was = user.balance
    user.update_attributes(balance: was + @transaction.price)
    @transaction.destroy
    flash[:success] = "Transaction deleted successfully"
    redirect_to transactions_url
    else
      flash[:info] = "Are yor ready to sign up the Warden? Log out this awesome test user if you are!"
      redirect_to transactions_url
    end
  end

  def data_filer_show
    @user = current_user
    @new = Transaction.new()
    if params['start'] =~ /[0-3]{1}[0-9]{1}\/[0-1]{1}[0-9]{1}\/[1-2]{1}[0-9]{3}/ && params['end'] =~ /[0-3]{1}[0-9]{1}\/[0-1]{1}[0-9]{1}\/[1-2]{1}[0-9]{3}/ && DateTime.parse(params['end'])>=DateTime.parse(params['start'])
      start_date = DateTime.parse(params['start'])
      end_date = DateTime.parse(params['end'])
      @transaction = Transaction.where(["created_at >= ? AND created_at <=? AND user_id =?", start_date, end_date, @user.id]).paginate(
                                                           :page => params[:page],
                                                           :per_page => 15).order('id DESC')
      render 'index'
    else
      flash[:danger] = "Wrong date format"
      redirect_to transactions_url
    end
  end

  def category_filter_show
    @new = Transaction.new()
    @user = current_user
    @transaction = Transaction.where(["kind_id = ? AND user_id =?", params[:transaction][:kind_id], @user.id]).paginate(:page => params[:page], :per_page => 15).order('id DESC')
    render 'index'
  end

  def money_filter_show
     arr=[]
    if params[:price] == "0"
      arr=[1000, 4000]
    else
      arr = params[:price].split(',')
    end
     @new = Transaction.new()
     @user = current_user
      @transaction = Transaction.where(["price >= ? AND price <=? AND user_id =?", arr.first, arr.last, @user.id]).paginate(:page => params[:page], :per_page => 15).order('id DESC')
      render 'index'
  end


  private
  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def transaction_params
      params.require(:transaction).permit(:name, :price, :kind, :kind_id)
  end

  def validate_end_date_before_start_date
    if end_date && start_date
      errors.add(:end_date, "Put error text here") if end_date < start_date
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_new.html.erb
<%= form_for(@new) do |f| %>

    <ul class="nav nav-pills">
    <li><%= f.label :name, class: 'form-control' %></li>
    <li><%= f.text_field :name, class: 'form-control' %></li>
    <li><%= f.label :price, class: 'form-control' %></li>
    <li><%= f.text_field :price, class: 'form-control' %></li>
          <li>  <select class="form-control" id="transaction_kind_id" name="transaction[kind_id]">
             <optgroup label="Required">
             <%= Kind.where(:user_id => @user.id, :isRequire=>true).each do |kind|%>
                 <option value= <%= kind.id  %>><%= kind.name %></option>
             <% end %>
             </optgroup>
             <optgroup label="Not required">
             <%= Kind.where(:user_id => @user.id, :isRequire=>false).each do |kind|%>
                 <option value= <%= kind.id  %>><%= kind.name %></option>
             <% end %>
             </optgroup>
           </select>
           </li>
    <li><%= f.submit "Add", class: "btn btn-primary" %></li>
    </ul>

<% end %>

app/views/transactions/edit.html.erb
<%= content_for :content do %>
    <h3>Edit transaction</h3>
    <%= form_for @transaction do |f| %>
        <%= render 'shared/transaction_error_messages' %>
        <ul class="nav nav-pills">
          <li><%= f.label :name, class: 'form-control' %></li>
          <li><%= f.text_field :name, class: 'form-control' %></li>
          <li><%= f.label :price, class: 'form-control' %></li>
          <li><%= f.text_field :price, class: 'form-control' %></li>
                <li>  <select class="form-control" id="transaction_kind_id" name="transaction[kind_id]">
                  <optgroup label="Required">
                    <%= Kind.where(:user_id => @user.id, :isRequire=>true).each do |kind|%>
                        <option value= <%= kind.id  %>><%= kind.name %></option>
                    <% end %>
                  </optgroup>
                  <optgroup label="Not required">
                    <%= Kind.where(:user_id => @user.id, :isRequire=>false).each do |kind|%>
                        <option value= <%= kind.id  %>><%= kind.name %></option>
                    <% end %>
                  </optgroup>
                </select>
                </li>
          <li><%= f.submit "Update", class: "btn btn-primary" %></li>
        </ul>
<% end %>
<% end %>

app/views/transactions/index.html.erb
<%= content_for :content do %>
    <h3>Transactions</h3>
    <%= render 'transactions/new' %>
    <% if current_page?(transactions_path) && @foo.any? %>
    <p>
    <h4>Require payments remaining in this month
    <% @foo.each do |name| %>
      <span class="label label-warning"> <%= name %></span>
    <% end %>
    </h4>
    </p>
    <% end %>

    <%= will_paginate @transaction %>
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Category</th>
        <th>Price</th>
        <th>Created_add</th>
        <th></th>
      </tr>

      <% @transaction.each do |transaction| %>
          <tr>
            <td><%= transaction.name %></td>
            <td>
              <%= if transaction.kind
                    transaction.kind.name
                  else
                    "Category was deleted"
                  end %>
            </td>
            <td> - <%= transaction.price %></td>
            <td><%= transaction.created_at %></td>
            <td><%= link_to "edit", edit_transaction_path(transaction) %></td>
            <td><%= link_to "delete", transaction, method: :delete,
                    data: { confirm: "You sure?" } %></td>
          </tr>
      <% end %>
    </table>
    <%= will_paginate @transaction %>
    <h4>Filters</h4>

    <%= form_tag data_filter_path, :method => :get do %>
        <ul class="nav nav-pills">
        <li><i class="fa fa-calendar form-control"></i></li>
        <li><%= text_field_tag 'start', 'Start date', class: "datepicker form-control" %></li>
        <li><%= text_field_tag 'end', 'End date', class: "datepicker form-control" %></li>
        <li><%= submit_tag 'Select', class: "btn btn-primary form-control" %></li>
       <% if current_page?(data_filter_path)  %> <span class="close"><%= link_to "<i class='fa fa-times'></i>".html_safe, transactions_url, class:"" %></span><% end %>
        </ul>
    <% end %>


    <%= form_tag category_filter_path, :method => :get do %>
     <ul class="nav nav-pills">
         <li><i class="fa fa-bookmark form-control"></i> </li>
               <li>  <select class="form-control" id="transaction_kind_id" name="transaction[kind_id]">
                 <optgroup label="Required">
                   <%= Kind.where(:user_id => @user.id, :isRequire=>true).each do |kind|%>
                       <option value= <%= kind.id  %>><%= kind.name %></option>
                   <% end %>
                 </optgroup>
                 <optgroup label="Not required">
                   <%= Kind.where(:user_id => @user.id, :isRequire=>false).each do |kind|%>
                       <option value= <%= kind.id  %>><%= kind.name %></option>
                   <% end %>
                 </optgroup>
               </select>
               </li>
         <li><%= submit_tag 'Select', class: "btn btn-primary form-control" %></li>
         <% if current_page?(category_filter_path)%><span class="close"><%= link_to "<i class='fa fa-times'></i>".html_safe, transactions_url, class:"" %></span><% end %>
    </ul>
    <% end %>

     <%= form_tag money_filter_path, :method => :get do |f| %>
           <ul class="nav nav-pills money-select">
             <li><i class="fa fa-usd form-control"></i> </li>
                 <li>
                   <%= text_field_tag :price, nil, id: 'ex', type: 'text', class:'slider form-control', value:'0'

                   %>
                 </li>
                 <li><%= submit_tag 'Select', class: "btn btn-primary form-control" %></li>
                       <% if current_page?(money_filter_path)  %>
                       <span class="close">
                       <%= link_to "<i class='fa fa-times'></i>".html_safe, transactions_url, class:"" %>
                       </span>
                        <% end %>
                         </ul>
                       <% end %>




<% end %>

app/views/transactions/new.html.erb
<%= content_for :content do %>
    <%= form_for(@transaction) do |f| %>
        <%= render 'shared/transaction_error_messages' %>

        <ul class="nav nav-pills">
          <li><%= f.label :name, class: 'form-control' %></li>
          <li><%= f.text_field :name, class: 'form-control' %></li>
          <li><%= f.label :price, class: 'form-control' %></li>
          <li><%= f.text_field :price, class: 'form-control' %></li>
          <li>  <select class="form-control" id="transaction_kind_id" name="transaction[kind_id]">
                <optgroup label="Required">
                    <%= Kind.where(:user_id => @user.id, :isRequire=>true).each do |kind|%>
                        <option value= <%= kind.id  %>><%= kind.name %></option>
                     <% end %>
                 </optgroup>
                 <optgroup label="Not required">
                     <%= Kind.where(:user_id => @user.id, :isRequire=>false).each do |kind|%>
                     <option value= <%= kind.id  %>><%= kind.name %></option>
                     <% end %>
                 </optgroup>
                 </select>
           </li>
           <li><%= f.submit "Add", class: "btn btn-primary" %></li>
         </ul>

    <% end %>
 <% end %>