config/routes.rb
Rails.application.routes.draw do
  get 'purposes/index'

  root             'static_pages#home'

  get 'signup'  => 'users#new'

  resources :users
  resources :kinds
  resources :transactions
  resources :purposes

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  post   'login'   => 'sessions#create'

  get   'test_user'   => 'sessions#login_test_user'

  get 'recharge' => 'users#recharge'
  post 'recharge' => 'users#add_money'

  get 'purpose_recharge' => 'purposes#recharge'
  post 'purpose_recharge' => 'purposes#add_money'



  get 'data-filter' => 'transactions#data_filer_show'
  get 'category-filter' => 'transactions#category_filter_show'
  get 'money-filter' => 'transactions#money_filter_show'

  get 'chart' => 'charts#index'
  get 'three_month' => 'charts#three_month'
  get 'month' => 'charts#month'
  get 'today' => 'charts#today'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
</footer>

app/views/layouts/_header.html.erb
  <div class="header">
  <h1>.warden</h1>
  </div>

app/views/layouts/_menu.html.erb
<ul class="nav nav-pills nav-stacked">
  <li> <%= link_to '<i class="fa fa-user fa-fw"></i> &nbsp;Profile'.html_safe, edit_user_path(current_user) %></li>
  <li> <%= link_to '<i class="fa fa-rocket fa-fw"></i> &nbsp;Transactions'.html_safe, transactions_path%></li>
  <li> <%= link_to '<i class="fa fa-external-link fa-fw"></i> &nbsp;Categories'.html_safe, kinds_path %></li>
  <li> <%= link_to '<i class="fa fa-bar-chart fa-fw"></i> &nbsp;Charts'.html_safe, chart_path %></li>
  <li> <%= link_to '<i class="fa fa-bicycle fa-fw"></i> &nbsp;Purposes'.html_safe, purposes_path %></li>
  <li> <%= link_to '<i class="fa fa-gears fa-fw"></i> &nbsp;Log out'.html_safe, logout_path, method: "delete" %></li>
</ul>

</ul>

app/views/layouts/application.html.erb
<% provide(:menu, "Home") %>
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Warden</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>




<% if logged_in? %>
  <%= render 'layouts/header' %>
  <div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<% end %>
    <% if logged_in? %>
    <div class="row">
      <div class="col-md-2">
        <%= render 'layouts/menu' %>
      </div>
      <div class="col-md-8 content">
        <%= render 'shared/error_messages' %>
        <%= yield(:content) %>
      </div>
      <div class="col-md-2">
        <%= render 'users/recharge' %>
      </div>
  <% else %>
    <% flash.each do |message_type, message| %>
        <div class="message alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
  <%= yield %>
  <% end %>



  <%= debug(params) if Rails.env.development? %>
</div></div>
</body>
</html>